### ISSUE TITLE
테스트코드 리펙토링, 백로그작성

### ISSUE THREAD

**Issue by cwangg897** [cwangg897/kusinsa#13]
### Tasks
- [ ] existsByName 으로 변경하기
- [ ] test코드 url 따로 빼도 됨 - 1/2 완료 User부분도 개선하기
- [ ] ~~test data sql파일로 넣어두는거 만들기~~
- [ ] ~~test파일에 고정된 유저나 만들어서 static으로 사용가능하게만들기~~
- [x] 백로그작성
