### ISSUE TITLE
실시간 랭킹

### ISSUE THREAD

**Issue by cwangg897** [cwangg897/kusinsa#23]
### OverView
실시간 랭킹으로 실시간으로 팔리는 Top 10과 조회되는 Top10을 보여주어야합니다
요구사항은 실시간 랭킹은 4시간 단위로 변경되도록 만드는것입니다. 

### Tasks
- [x] 실시간 조회 Top 10  (컨트롤러까지 Response로)
- [x] 실시간 판매 Top 10 
- [x] 지금까지 밀린 기술글 작성하기
